version: "3.9"
networks:
 roboshop:
  driver: bridge
services:
 web:
  image: web:v1
  container_name: web
  ports:
  - "80:80"
  depends_on:
  - catalogue
  - user
  - cart
  - mysql
  - shipping
 mongodb:
  image: sekharmanduri/mongodb:v1
  container_name: mongodb
 catalogue:
  image: sekharmanduri/catalogue:v1
  container_name: catalogue
  depends_on:
  - mongodb
 redis:
  image:redis
 user:
  image: sekharmanduri/user:v1
  container_name: user
  depends_on:
  - mongodb
  - redis
 cart:
  image: sekharmanduri/cart:v2
  container_name: cart
  depends_on:
  - redis
  - catalogue
 mysql:
  image: sekharmanduri/mysql:v1
  container_name: mysql
 shipping:
  images: sekharmanduri/shipping:v2
  container_name: shipping
  depends_on:
  - mysql
 rabbitmq:
  image: rabbitmq
  container_name: rabbitmq
 payment:
  image: sekharmanduri/payment:v1
  container_name: payment
  depends_on: 
  - rabbitmq
ratings:
 image: sekharmanduri/ratings:v1
 container_name: ratings
 depends_on:
 - mysql




